const buttons = [
    {
        "name": "Nút cơ bản",
        "code": "<button class=\"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded\">Nút cơ bản</button>",
        "classes": "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
    },
    {
        "name": "Nút Lượng Tử",
        "code": "<button class=\"relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out border-2 border-purple-500 rounded-full shadow-md group\">\n  <span class=\"absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full bg-gradient-to-r from-purple-600 to-blue-400 group-hover:translate-x-0 ease\">\n  <svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14 5l7 7m0 0l-7 7m7-7H3\"></path></svg>\n  </span>\n  <span class=\"absolute flex items-center justify-center w-full h-full text-purple-600 transition-all duration-300 transform group-hover:translate-x-full ease\">Nút Lượng Tử</span>\n  <span class=\"relative invisible\">Nút Lượng Tử</span>\n</button>",
        "classes": "relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out border-2 border-purple-500 rounded-full shadow-md group"
    },
    {
        "name": "Nút Siêu Thanh",
        "code": "<button class=\"relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out border-2 border-purple-500 rounded-full shadow-md group\">\n  <span class=\"absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full bg-gradient-to-r from-purple-600 to-blue-400 group-hover:translate-x-0 ease\">\n  <svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14 5l7 7m0 0l-7 7m7-7H3\"></path></svg>\n  </span>\n  <span class=\"absolute flex items-center justify-center w-full h-full text-purple-600 transition-all duration-300 ease-in-out group-hover:translate-x-full\">\n  <span class=\"mr-2\">Siêu</span> Thanh\n  </span>\n  <span class=\"relative invisible\">\n  <span class=\"mr-2\">Siêu</span> Thanh\n  </span>\n</button>",
        "classes": "relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out border-2 border-purple-500 rounded-full shadow-md group"
    },
    {
        "name": "Nút Thiên Hà",
        "code": "<button class=\"relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 scale-100 hover:scale-110 active:scale-90 transition-transform duration-300 ease-in-out\">\n  <span class=\"relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0\">\n    Khám phá Vũ Trụ\n  </span>\n</button>",
        "classes": "relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 scale-100 hover:scale-110 active:scale-90 transition-transform duration-300 ease-in-out"
    },
    {
        "name": "Nút Biến Hình",
        "code": "<button class=\"relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-pink-600 transition duration-500 ease-in-out transform border-2 border-double border-pink-300 rounded-3xl bg-gradient-to-r from-yellow-300 via-pink-400 to-purple-500 hover:scale-105 hover:rotate-3 hover:bg-gradient-to-br hover:from-purple-500 hover:via-pink-400 hover:to-yellow-300 active:scale-95 active:-rotate-2 active:bg-gradient-to-tl active:from-yellow-300 active:via-pink-400 active:to-purple-500 focus:outline-none focus:ring-4 focus:ring-pink-200 shadow-lg\">Biến Hình</button>",
        "classes": "relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-pink-600 transition duration-500 ease-in-out transform border-2 border-double border-pink-300 rounded-3xl bg-gradient-to-r from-yellow-300 via-pink-400 to-purple-500 hover:scale-105 hover:rotate-3 hover:bg-gradient-to-br hover:from-purple-500 hover:via-pink-400 hover:to-yellow-300 active:scale-95 active:-rotate-2 active:bg-gradient-to-tl active:from-yellow-300 active:via-pink-400 active:to-purple-500 focus:outline-none focus:ring-4 focus:ring-pink-200 shadow-lg"
    },
    {
        "name": "Nút Phản Quang",
        "code": "<button class=\"relative inline-flex items-center justify-center p-5 px-8 py-4 overflow-hidden font-bold text-teal-600 transition duration-700 ease-in-out transform bg-gradient-to-r from-lime-300 via-cyan-400 to-teal-500 hover:bg-gradient-to-br hover:from-teal-500 hover:via-cyan-400 hover:to-lime-300 active:scale-90 active:-rotate-2 active:bg-gradient-to-tl active:from-lime-300 active:via-cyan-400 active:to-teal-500 focus:outline-none focus:ring-4 focus:ring-cyan-200 shadow-2xl rounded-xl border-4 border-dotted border-lime-400 hover:border-dashed hover:border-cyan-400 hover:-translate-y-1 hover:scale-110 active:translate-y-1 active:scale-95 clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-sm\">Phản Quang</button>",
        "classes": "relative inline-flex items-center justify-center p-5 px-8 py-4 overflow-hidden font-bold text-teal-600 transition duration-700 ease-in-out transform bg-gradient-to-r from-lime-300 via-cyan-400 to-teal-500 hover:bg-gradient-to-br hover:from-teal-500 hover:via-cyan-400 hover:to-lime-300 active:scale-90 active:-rotate-2 active:bg-gradient-to-tl active:from-lime-300 active:via-cyan-400 active:to-teal-500 focus:outline-none focus:ring-4 focus:ring-cyan-200 shadow-2xl rounded-xl border-4 border-dotted border-lime-400 hover:border-dashed hover:border-cyan-400 hover:-translate-y-1 hover:scale-110 active:translate-y-1 active:scale-95 clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-sm"
    },
    {
        "name": "Nút Ma Trận",
        "code": "<button class=\"relative inline-flex items-center justify-center p-6 overflow-hidden font-mono text-lg text-green-300 transition duration-1000 ease-in-out transform bg-gradient-to-br from-gray-800 via-green-700 to-green-900 border-0 rounded-xl shadow-2xl group hover:rotate-12 hover:scale-110 hover:bg-gradient-to-tl hover:from-green-900 hover:via-green-700 hover:to-gray-800 active:scale-90 active:-rotate-3 active:bg-gradient-to-tr active:from-green-900 active:via-green-700 active:to-gray-800 focus:outline-none focus:ring-4 focus:ring-green-400 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-green-400 before:to-transparent before:opacity-20 before:-translate-x-full before:animate-slidein before:group-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-green-500 after:rounded-xl after:opacity-30 after:animate-pulse after:group-hover:opacity-100 after:-translate-x-full after:group-hover:translate-x-full clip-path-polygon(10% 0%, 90% 0%, 100% 10%, 100% 90%, 90% 100%, 10% 100%, 0% 90%, 0% 10%) backdrop-filter backdrop-blur-lg\">\n  <span class=\"relative z-10\">Truy Cập</span>\n</button>",
        "classes": "relative inline-flex items-center justify-center p-6 overflow-hidden font-mono text-lg text-green-300 transition duration-1000 ease-in-out transform bg-gradient-to-br from-gray-800 via-green-700 to-green-900 border-0 rounded-xl shadow-2xl group hover:rotate-12 hover:scale-110 hover:bg-gradient-to-tl hover:from-green-900 hover:via-green-700 hover:to-gray-800 active:scale-90 active:-rotate-3 active:bg-gradient-to-tr active:from-green-900 active:via-green-700 active:to-gray-800 focus:outline-none focus:ring-4 focus:ring-green-400 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-green-400 before:to-transparent before:opacity-20 before:-translate-x-full before:animate-slidein before:group-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-green-500 after:rounded-xl after:opacity-30 after:animate-pulse after:group-hover:opacity-100 after:-translate-x-full after:group-hover:translate-x-full clip-path-polygon(10% 0%, 90% 0%, 100% 10%, 100% 90%, 90% 100%, 10% 100%, 0% 90%, 0% 10%) backdrop-filter backdrop-blur-lg"
    },
    {
        "name": "Nút Tinh Vân",
        "code": "<button class=\"relative inline-flex items-center justify-center p-5 px-12 py-5 overflow-hidden font-semibold text-amber-50 bg-gradient-to-r from-indigo-900 via-purple-600 to-pink-700 rounded-3xl border-4 border-double border-amber-300 shadow-xl transition-all duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-105 hover:shadow-2xl hover:bg-gradient-to-br active:translate-y-1 active:scale-95 active:shadow-sm active:bg-gradient-to-tl focus:outline-none focus:ring-4 focus:ring-amber-300 clip-path-polygon(20% 0%, 80% 0%, 100% 30%, 100% 70%, 80% 100%, 20% 100%, 0% 70%, 0% 30%) backdrop-filter backdrop-blur-md\">Khám phá</button>",
        "classes": "relative inline-flex items-center justify-center p-5 px-12 py-5 overflow-hidden font-semibold text-amber-50 bg-gradient-to-r from-indigo-900 via-purple-600 to-pink-700 rounded-3xl border-4 border-double border-amber-300 shadow-xl transition-all duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-105 hover:shadow-2xl hover:bg-gradient-to-br active:translate-y-1 active:scale-95 active:shadow-sm active:bg-gradient-to-tl focus:outline-none focus:ring-4 focus:ring-amber-300 clip-path-polygon(20% 0%, 80% 0%, 100% 30%, 100% 70%, 80% 100%, 20% 100%, 0% 70%, 0% 30%) backdrop-filter backdrop-blur-md"
    }
];

export default buttons;
