const buttons = [
    {
        "name": "Nút cơ bản",
        "code": "<button class=\"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded\">Nút cơ bản</button>",
        "classes": "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
    },
    {
        "name": "Nút Lượng Tử",
        "code": "<button class=\"relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out border-2 border-purple-500 rounded-full shadow-md group\">\n  <span class=\"absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full bg-gradient-to-r from-purple-600 to-blue-400 group-hover:translate-x-0 ease\">\n  <svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14 5l7 7m0 0l-7 7m7-7H3\"></path></svg>\n  </span>\n  <span class=\"absolute flex items-center justify-center w-full h-full text-purple-600 transition-all duration-300 transform group-hover:translate-x-full ease\">Nút Lượng Tử</span>\n  <span class=\"relative invisible\">Nút Lượng Tử</span>\n</button>",
        "classes": "relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out border-2 border-purple-500 rounded-full shadow-md group"
    },
    {
        "name": "Nút Siêu Thanh",
        "code": "<button class=\"relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out border-2 border-purple-500 rounded-full shadow-md group\">\n  <span class=\"absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full bg-gradient-to-r from-purple-600 to-blue-400 group-hover:translate-x-0 ease\">\n  <svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14 5l7 7m0 0l-7 7m7-7H3\"></path></svg>\n  </span>\n  <span class=\"absolute flex items-center justify-center w-full h-full text-purple-600 transition-all duration-300 ease-in-out group-hover:translate-x-full\">\n  <span class=\"mr-2\">Siêu</span> Thanh\n  </span>\n  <span class=\"relative invisible\">\n  <span class=\"mr-2\">Siêu</span> Thanh\n  </span>\n</button>",
        "classes": "relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out border-2 border-purple-500 rounded-full shadow-md group"
    },
    {
        "name": "Nút Thiên Hà",
        "code": "<button class=\"relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 scale-100 hover:scale-110 active:scale-90 transition-transform duration-300 ease-in-out\">\n  <span class=\"relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0\">\n    Khám phá Vũ Trụ\n  </span>\n</button>",
        "classes": "relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 scale-100 hover:scale-110 active:scale-90 transition-transform duration-300 ease-in-out"
    },
    {
        "name": "Nút Biến Hình",
        "code": "<button class=\"relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-pink-600 transition duration-500 ease-in-out transform border-2 border-double border-pink-300 rounded-3xl bg-gradient-to-r from-yellow-300 via-pink-400 to-purple-500 hover:scale-105 hover:rotate-3 hover:bg-gradient-to-br hover:from-purple-500 hover:via-pink-400 hover:to-yellow-300 active:scale-95 active:-rotate-2 active:bg-gradient-to-tl active:from-yellow-300 active:via-pink-400 active:to-purple-500 focus:outline-none focus:ring-4 focus:ring-pink-200 shadow-lg\">Biến Hình</button>",
        "classes": "relative inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-pink-600 transition duration-500 ease-in-out transform border-2 border-double border-pink-300 rounded-3xl bg-gradient-to-r from-yellow-300 via-pink-400 to-purple-500 hover:scale-105 hover:rotate-3 hover:bg-gradient-to-br hover:from-purple-500 hover:via-pink-400 hover:to-yellow-300 active:scale-95 active:-rotate-2 active:bg-gradient-to-tl active:from-yellow-300 active:via-pink-400 active:to-purple-500 focus:outline-none focus:ring-4 focus:ring-pink-200 shadow-lg"
    },
    {
        "name": "Nút Phản Quang",
        "code": "<button class=\"relative inline-flex items-center justify-center p-5 px-8 py-4 overflow-hidden font-bold text-teal-600 transition duration-700 ease-in-out transform bg-gradient-to-r from-lime-300 via-cyan-400 to-teal-500 hover:bg-gradient-to-br hover:from-teal-500 hover:via-cyan-400 hover:to-lime-300 active:scale-90 active:-rotate-2 active:bg-gradient-to-tl active:from-lime-300 active:via-cyan-400 active:to-teal-500 focus:outline-none focus:ring-4 focus:ring-cyan-200 shadow-2xl rounded-xl border-4 border-dotted border-lime-400 hover:border-dashed hover:border-cyan-400 hover:-translate-y-1 hover:scale-110 active:translate-y-1 active:scale-95 clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-sm\">Phản Quang</button>",
        "classes": "relative inline-flex items-center justify-center p-5 px-8 py-4 overflow-hidden font-bold text-teal-600 transition duration-700 ease-in-out transform bg-gradient-to-r from-lime-300 via-cyan-400 to-teal-500 hover:bg-gradient-to-br hover:from-teal-500 hover:via-cyan-400 hover:to-lime-300 active:scale-90 active:-rotate-2 active:bg-gradient-to-tl active:from-lime-300 active:via-cyan-400 active:to-teal-500 focus:outline-none focus:ring-4 focus:ring-cyan-200 shadow-2xl rounded-xl border-4 border-dotted border-lime-400 hover:border-dashed hover:border-cyan-400 hover:-translate-y-1 hover:scale-110 active:translate-y-1 active:scale-95 clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-sm"
    },
    {
        "name": "Nút Ma Trận",
        "code": "<button class=\"relative inline-flex items-center justify-center p-6 overflow-hidden font-mono text-lg text-green-300 transition duration-1000 ease-in-out transform bg-gradient-to-br from-gray-800 via-green-700 to-green-900 border-0 rounded-xl shadow-2xl group hover:rotate-12 hover:scale-110 hover:bg-gradient-to-tl hover:from-green-900 hover:via-green-700 hover:to-gray-800 active:scale-90 active:-rotate-3 active:bg-gradient-to-tr active:from-green-900 active:via-green-700 active:to-gray-800 focus:outline-none focus:ring-4 focus:ring-green-400 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-green-400 before:to-transparent before:opacity-20 before:-translate-x-full before:animate-slidein before:group-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-green-500 after:rounded-xl after:opacity-30 after:animate-pulse after:group-hover:opacity-100 after:-translate-x-full after:group-hover:translate-x-full clip-path-polygon(10% 0%, 90% 0%, 100% 10%, 100% 90%, 90% 100%, 10% 100%, 0% 90%, 0% 10%) backdrop-filter backdrop-blur-lg\">\n  <span class=\"relative z-10\">Truy Cập</span>\n</button>",
        "classes": "relative inline-flex items-center justify-center p-6 overflow-hidden font-mono text-lg text-green-300 transition duration-1000 ease-in-out transform bg-gradient-to-br from-gray-800 via-green-700 to-green-900 border-0 rounded-xl shadow-2xl group hover:rotate-12 hover:scale-110 hover:bg-gradient-to-tl hover:from-green-900 hover:via-green-700 hover:to-gray-800 active:scale-90 active:-rotate-3 active:bg-gradient-to-tr active:from-green-900 active:via-green-700 active:to-gray-800 focus:outline-none focus:ring-4 focus:ring-green-400 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-green-400 before:to-transparent before:opacity-20 before:-translate-x-full before:animate-slidein before:group-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-green-500 after:rounded-xl after:opacity-30 after:animate-pulse after:group-hover:opacity-100 after:-translate-x-full after:group-hover:translate-x-full clip-path-polygon(10% 0%, 90% 0%, 100% 10%, 100% 90%, 90% 100%, 10% 100%, 0% 90%, 0% 10%) backdrop-filter backdrop-blur-lg"
    },
    {
        "name": "Nút Tinh Vân",
        "code": "<button class=\"relative inline-flex items-center justify-center p-5 px-12 py-5 overflow-hidden font-semibold text-amber-50 bg-gradient-to-r from-indigo-900 via-purple-600 to-pink-700 rounded-3xl border-4 border-double border-amber-300 shadow-xl transition-all duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-105 hover:shadow-2xl hover:bg-gradient-to-br active:translate-y-1 active:scale-95 active:shadow-sm active:bg-gradient-to-tl focus:outline-none focus:ring-4 focus:ring-amber-300 clip-path-polygon(20% 0%, 80% 0%, 100% 30%, 100% 70%, 80% 100%, 20% 100%, 0% 70%, 0% 30%) backdrop-filter backdrop-blur-md\">Khám phá</button>",
        "classes": "relative inline-flex items-center justify-center p-5 px-12 py-5 overflow-hidden font-semibold text-amber-50 bg-gradient-to-r from-indigo-900 via-purple-600 to-pink-700 rounded-3xl border-4 border-double border-amber-300 shadow-xl transition-all duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-105 hover:shadow-2xl hover:bg-gradient-to-br active:translate-y-1 active:scale-95 active:shadow-sm active:bg-gradient-to-tl focus:outline-none focus:ring-4 focus:ring-amber-300 clip-path-polygon(20% 0%, 80% 0%, 100% 30%, 100% 70%, 80% 100%, 20% 100%, 0% 70%, 0% 30%) backdrop-filter backdrop-blur-md"
    },
    {
        "name": "Nút Vô Cực",
        "code": "<button class=\"relative inline-flex items-center justify-center p-8 px-10 py-6 overflow-hidden font-serif text-xl text-orange-300 bg-gradient-to-tr from-slate-900 via-amber-700 to-slate-900 rounded-full border-8 border-double border-orange-500 shadow-2xl transition-all duration-700 ease-in-out transform hover:-translate-y-2 hover:scale-110 hover:rotate-3 hover:bg-gradient-to-tl hover:shadow-inner active:translate-y-2 active:scale-95 active:-rotate-3 active:bg-gradient-to-br active:shadow-sm focus:outline-none focus:ring-8 focus:ring-orange-400 clip-path-polygon(50% 0%, 90% 20%, 100% 60%, 75% 100%, 25% 100%, 0% 60%, 10% 20%) backdrop-filter backdrop-blur-md hover:border-dotted\">Vô Cực</button>",
        "classes": "relative inline-flex items-center justify-center p-8 px-10 py-6 overflow-hidden font-serif text-xl text-orange-300 bg-gradient-to-tr from-slate-900 via-amber-700 to-slate-900 rounded-full border-8 border-double border-orange-500 shadow-2xl transition-all duration-700 ease-in-out transform hover:-translate-y-2 hover:scale-110 hover:rotate-3 hover:bg-gradient-to-tl hover:shadow-inner active:translate-y-2 active:scale-95 active:-rotate-3 active:bg-gradient-to-br active:shadow-sm focus:outline-none focus:ring-8 focus:ring-orange-400 clip-path-polygon(50% 0%, 90% 20%, 100% 60%, 75% 100%, 25% 100%, 0% 60%, 10% 20%) backdrop-filter backdrop-blur-md hover:border-dotted"
    },
    {
        "name": "Nút Hoa Văn",
        "code": "<button class=\"relative inline-flex items-center justify-center p-6 overflow-hidden font-sans text-lg text-fuchsia-300 transition duration-1000 ease-in-out transform bg-gradient-to-r from-rose-900 via-fuchsia-700 to-violet-900 border-0 rounded-xl shadow-2xl group hover:rotate-6 hover:scale-105 hover:bg-gradient-to-bl hover:from-violet-900 hover:via-fuchsia-700 hover:to-rose-900 active:scale-95 active:-rotate-3 active:bg-gradient-to-tr active:from-violet-900 active:via-fuchsia-700 active:to-rose-900 focus:outline-none focus:ring-4 focus:ring-fuchsia-400 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-fuchsia-400 before:to-transparent before:opacity-30 before:-translate-x-full before:animate-pulse before:group-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dashed after:border-fuchsia-600 after:rounded-xl after:opacity-40 after:animate-pulse after:group-hover:opacity-100 after:-translate-x-full after:group-hover:translate-x-full clip-path-polygon(25% 0%, 100% 0%, 75% 100%, 0% 100%) hover:clip-path-polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%) backdrop-filter backdrop-blur-md\">Nội dung nút</button>",
        "classes": "relative inline-flex items-center justify-center p-6 overflow-hidden font-sans text-lg text-fuchsia-300 transition duration-1000 ease-in-out transform bg-gradient-to-r from-rose-900 via-fuchsia-700 to-violet-900 border-0 rounded-xl shadow-2xl group hover:rotate-6 hover:scale-105 hover:bg-gradient-to-bl hover:from-violet-900 hover:via-fuchsia-700 hover:to-rose-900 active:scale-95 active:-rotate-3 active:bg-gradient-to-tr active:from-violet-900 active:via-fuchsia-700 active:to-rose-900 focus:outline-none focus:ring-4 focus:ring-fuchsia-400 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-fuchsia-400 before:to-transparent before:opacity-30 before:-translate-x-full before:animate-pulse before:group-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dashed after:border-fuchsia-600 after:rounded-xl after:opacity-40 after:animate-pulse after:group-hover:opacity-100 after:-translate-x-full after:group-hover:translate-x-full clip-path-polygon(25% 0%, 100% 0%, 75% 100%, 0% 100%) hover:clip-path-polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%) backdrop-filter backdrop-blur-md"
    },
    {
        "name": "Nút Nhật Thực",
        "code": "<button class=\"relative inline-flex items-center justify-center p-8 px-12 py-7 overflow-hidden font-display text-3xl text-sky-200 bg-gradient-to-r from-gray-900 via-indigo-600 to-sky-400 rounded-full border-8 border-double border-gray-600 shadow-3xl transition-all duration-700 ease-in-out transform hover:-translate-y-2 hover:scale-110 hover:rotate-12 hover:bg-gradient-to-tl hover:shadow-inner hover:border-dotted hover:border-sky-300 active:translate-y-2 active:scale-95 active:-rotate-6 active:bg-gradient-to-br active:shadow-sm active:border-dashed active:border-indigo-400 focus:outline-none focus:ring-8 focus:ring-sky-300 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-sky-200 before:to-transparent before:opacity-40 before:-translate-x-full before:animate-pulse before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dashed after:border-indigo-300 after:rounded-full after:opacity-50 after:animate-pulse after:-translate-x-full after-hover:translate-x-full clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-lg\">Nhấn Vào!</button>",
        "classes": "relative inline-flex items-center justify-center p-8 px-12 py-7 overflow-hidden font-display text-3xl text-sky-200 bg-gradient-to-r from-gray-900 via-indigo-600 to-sky-400 rounded-full border-8 border-double border-gray-600 shadow-3xl transition-all duration-700 ease-in-out transform hover:-translate-y-2 hover:scale-110 hover:rotate-12 hover:bg-gradient-to-tl hover:shadow-inner hover:border-dotted hover:border-sky-300 active:translate-y-2 active:scale-95 active:-rotate-6 active:bg-gradient-to-br active:shadow-sm active:border-dashed active:border-indigo-400 focus:outline-none focus:ring-8 focus:ring-sky-300 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-sky-200 before:to-transparent before:opacity-40 before:-translate-x-full before:animate-pulse before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dashed after:border-indigo-300 after:rounded-full after:opacity-50 after:animate-pulse after:-translate-x-full after-hover:translate-x-full clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-lg"
    },
    {
        "name": "Nút Lửa Phượng Hoàng",
        "code": "<button class=\"relative inline-flex items-center justify-center p-10 px-16 py-8 overflow-hidden font-serif text-4xl text-red-100 bg-gradient-to-r from-yellow-100 via-orange-400 to-red-600 rounded-xl border-8 border-double border-yellow-300 shadow-2xl transition-all duration-1000 ease-in-out transform hover:-translate-y-3 hover:scale-110 hover:rotate-6 hover:bg-gradient-to-tl hover:shadow-inner active:translate-y-3 active:scale-95 active:-rotate-6 active:bg-gradient-to-br active:shadow-sm focus:outline-none focus:ring-8 focus:ring-red-300 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-yellow-200 before:to-transparent before:opacity-50 before:-translate-x-full before:animate-pulse-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-orange-500 after:rounded-xl after:opacity-60 after:animate-pulse-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(5% 20%, 30% 0%, 70% 0%, 95% 20%, 100% 50%, 95% 80%, 70% 100%, 30% 100%, 5% 80%) backdrop-filter backdrop-blur-xl hover:border-solid hover:border-red-400\">Phượng Hoàng Lửa</button>",
        "classes": "relative inline-flex items-center justify-center p-10 px-16 py-8 overflow-hidden font-serif text-4xl text-red-100 bg-gradient-to-r from-yellow-100 via-orange-400 to-red-600 rounded-xl border-8 border-double border-yellow-300 shadow-2xl transition-all duration-1000 ease-in-out transform hover:-translate-y-3 hover:scale-110 hover:rotate-6 hover:bg-gradient-to-tl hover:shadow-inner active:translate-y-3 active:scale-95 active:-rotate-6 active:bg-gradient-to-br active:shadow-sm focus:outline-none focus:ring-8 focus:ring-red-300 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-yellow-200 before:to-transparent before:opacity-50 before:-translate-x-full before:animate-pulse-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-orange-500 after:rounded-xl after:opacity-60 after:animate-pulse-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(5% 20%, 30% 0%, 70% 0%, 95% 20%, 100% 50%, 95% 80%, 70% 100%, 30% 100%, 5% 80%) backdrop-filter backdrop-blur-xl hover:border-solid hover:border-red-400"
    },
    {
        "name": "Nút Đa Sắc",
        "code": "<button class=\"relative inline-flex items-center justify-center p-8 px-14 py-9 overflow-hidden font-semibold text-lg text-white bg-gradient-to-r from-emerald-200 via-teal-400 to-blue-600 via-purple-800 to-pink-500 rounded-3xl border-4 border-solid border-transparent shadow-2xl transition-all duration-700 ease-in-out transform hover:-translate-y-1 hover:scale-105 hover:rotate-2 hover:shadow-xl hover:border-emerald-300 active:translate-y-1 active:scale-95 active:-rotate-1 active:shadow-sm active:border-pink-400 focus:outline-none focus:ring-8 focus:ring-blue-300 before:absolute before:inset-0 before:bg-gradient-to-br before:from-transparent before:via-teal-200 before:to-transparent before:opacity-60 before:-translate-x-full before:animate-glitter-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dashed after:border-blue-400 after:rounded-3xl after:opacity-70 after:animate-glitter-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(15% 0%, 85% 0%, 100% 30%, 100% 70%, 85% 100%, 15% 100%, 0% 70%, 0% 30%) backdrop-filter backdrop-blur-md hover:border-double hover:border-purple-500\">\n  <span class=\"relative z-10\">Khám phá</span>\n</button>",
        "classes": "relative inline-flex items-center justify-center p-8 px-14 py-9 overflow-hidden font-semibold text-lg text-white bg-gradient-to-r from-emerald-200 via-teal-400 to-blue-600 via-purple-800 to-pink-500 rounded-3xl border-4 border-solid border-transparent shadow-2xl transition-all duration-700 ease-in-out transform hover:-translate-y-1 hover:scale-105 hover:rotate-2 hover:shadow-xl hover:border-emerald-300 active:translate-y-1 active:scale-95 active:-rotate-1 active:shadow-sm active:border-pink-400 focus:outline-none focus:ring-8 focus:ring-blue-300 before:absolute before:inset-0 before:bg-gradient-to-br before:from-transparent before:via-teal-200 before:to-transparent before:opacity-60 before:-translate-x-full before:animate-glitter-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dashed after:border-blue-400 after:rounded-3xl after:opacity-70 after:animate-glitter-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(15% 0%, 85% 0%, 100% 30%, 100% 70%, 85% 100%, 15% 100%, 0% 70%, 0% 30%) backdrop-filter backdrop-blur-md hover:border-double hover:border-purple-500"
    },
    {
        "name": "Nút Hắc Ám",
        "code": "<button class=\"relative inline-flex items-center justify-center p-12 px-16 py-10 overflow-hidden font-mono text-4xl text-gray-200 bg-gradient-to-tl from-indigo-300 via-gray-900 to-black rounded-2xl border-8 border-double border-gray-700 shadow-3xl transition-all duration-1000 ease-in-out transform hover:-translate-y-4 hover:scale-110 hover:rotate-1 hover:bg-gradient-to-br hover:shadow-inner hover:border-indigo-400 active:translate-y-4 active:scale-95 active:-rotate-1 active:bg-gradient-to-tr active:shadow-sm active:border-gray-500 focus:outline-none focus:ring-8 focus:ring-gray-600 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-gray-400 before:to-transparent before:opacity-70 before:-translate-x-full before:animate-glow-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-gray-600 after:rounded-2xl after:opacity-80 after:animate-glow-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(5% 25%, 30% 5%, 70% 5%, 95% 25%, 100% 50%, 95% 75%, 70% 95%, 30% 95%, 5% 75%) backdrop-filter backdrop-blur-3xl hover:border-dashed hover:border-black \">Hắc Ám</button>",
        "classes": "relative inline-flex items-center justify-center p-12 px-16 py-10 overflow-hidden font-mono text-4xl text-gray-200 bg-gradient-to-tl from-indigo-300 via-gray-900 to-black rounded-2xl border-8 border-double border-gray-700 shadow-3xl transition-all duration-1000 ease-in-out transform hover:-translate-y-4 hover:scale-110 hover:rotate-1 hover:bg-gradient-to-br hover:shadow-inner hover:border-indigo-400 active:translate-y-4 active:scale-95 active:-rotate-1 active:bg-gradient-to-tr active:shadow-sm active:border-gray-500 focus:outline-none focus:ring-8 focus:ring-gray-600 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-gray-400 before:to-transparent before:opacity-70 before:-translate-x-full before:animate-glow-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-gray-600 after:rounded-2xl after:opacity-80 after:animate-glow-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(5% 25%, 30% 5%, 70% 5%, 95% 25%, 100% 50%, 95% 75%, 70% 95%, 30% 95%, 5% 75%) backdrop-filter backdrop-blur-3xl hover:border-dashed hover:border-black"
    },
    {
        "name": "Nút Sao Băng",
        "code": "<button class=\"relative inline-flex items-center justify-center p-7 px-12 py-8 overflow-hidden font-sans text-3xl text-white bg-gradient-to-r from-indigo-200 via-purple-400 to-pink-600 rounded-xl border-4 border-solid border-transparent shadow-2xl transition-all duration-700 ease-in-out transform hover:-translate-y-2 hover:scale-110 hover:rotate-3 hover:shadow-xl hover:border-white active:translate-y-2 active:scale-95 active:-rotate-3 active:shadow-sm active:border-yellow-400 focus:outline-none focus:ring-8 focus:ring-violet-300 before:absolute before:inset-0 before:bg-gradient-to-br before:from-transparent before:via-yellow-100 before:to-transparent before:opacity-70 before:-translate-x-full before:animate-shimmer-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-amber-300 after:rounded-xl after:opacity-80 after:animate-shimmer-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(50% 0%, 90% 20%, 100% 60%, 75% 100%, 25% 100%, 0% 60%, 10% 20%) backdrop-filter backdrop-blur-md hover:border-double hover:border-yellow-300\">Vụt Sáng</button>",
        "classes": "relative inline-flex items-center justify-center p-7 px-12 py-8 overflow-hidden font-sans text-3xl text-white bg-gradient-to-r from-indigo-200 via-purple-400 to-pink-600 rounded-xl border-4 border-solid border-transparent shadow-2xl transition-all duration-700 ease-in-out transform hover:-translate-y-2 hover:scale-110 hover:rotate-3 hover:shadow-xl hover:border-white active:translate-y-2 active:scale-95 active:-rotate-3 active:shadow-sm active:border-yellow-400 focus:outline-none focus:ring-8 focus:ring-violet-300 before:absolute before:inset-0 before:bg-gradient-to-br before:from-transparent before:via-yellow-100 before:to-transparent before:opacity-70 before:-translate-x-full before:animate-shimmer-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-amber-300 after:rounded-xl after:opacity-80 after:animate-shimmer-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(50% 0%, 90% 20%, 100% 60%, 75% 100%, 25% 100%, 0% 60%, 10% 20%) backdrop-filter backdrop-blur-md hover:border-double hover:border-yellow-300"
    },
    {
        "name": "Nút Nguyệt Thực",
        "code": "<button class=\"relative inline-flex items-center justify-center p-10 px-20 py-12 overflow-hidden font-serif text-5xl text-white bg-gradient-to-br from-indigo-950 via-slate-50 to-orange-500 rounded-full border-8 border-double border-blue-200 shadow-2xl transition-all duration-700 ease-in-out transform hover:-translate-y-3 hover:scale-115 hover:rotate-12 hover:bg-gradient-to-tl hover:shadow-inner hover:border-dotted hover:border-yellow-200 active:translate-y-3 active:scale-90 active:-rotate-6 active:bg-gradient-to-tr active:shadow-sm active:border-dashed active:border-pink-300 focus:outline-none focus:ring-8 focus:ring-fuchsia-400 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-cyan-400 before:to-transparent before:opacity-40 before:-translate-x-full before:animate-meteor before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-lime-400 after:rounded-full after:opacity-60 after:animate-pulse after:-translate-x-full after-hover:translate-x-full clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-xl hover:clip-path-polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%)\">Nguyệt Thực</button>",
        "classes": "relative inline-flex items-center justify-center p-10 px-20 py-12 overflow-hidden font-serif text-5xl text-white bg-gradient-to-br from-indigo-950 via-slate-50 to-orange-500 rounded-full border-8 border-double border-blue-200 shadow-2xl transition-all duration-700 ease-in-out transform hover:-translate-y-3 hover:scale-115 hover:rotate-12 hover:bg-gradient-to-tl hover:shadow-inner hover:border-dotted hover:border-yellow-200 active:translate-y-3 active:scale-90 active:-rotate-6 active:bg-gradient-to-tr active:shadow-sm active:border-dashed active:border-pink-300 focus:outline-none focus:ring-8 focus:ring-fuchsia-400 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-cyan-400 before:to-transparent before:opacity-40 before:-translate-x-full before:animate-meteor before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-lime-400 after:rounded-full after:opacity-60 after:animate-pulse after:-translate-x-full after-hover:translate-x-full clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-xl hover:clip-path-polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%)"
    },
    {
        "name": "Nút Chấn động Âm thanh",
        "code": "<button class=\"relative inline-flex items-center justify-center p-8 px-16 py-10 overflow-hidden font-display text-4xl text-turquoise-100 bg-gradient-to-r from-indigo-800 via-turquoise-400 to-yellow-500 rounded-3xl border-8 border-dashed border-yellow-300 shadow-3xl transition-all duration-1000 ease-in-out transform hover:-translate-y-4 hover:scale-110 hover:rotate-3 hover:bg-gradient-to-tl hover:shadow-2xl hover:border-double hover:border-turquoise-400 active:translate-y-4 active:scale-90 active:-rotate-3 active:bg-gradient-to-tr active:shadow-sm active:border-dotted active:border-indigo-800 focus:outline-none focus:ring-8 focus:ring-yellow-400 before:absolute before:inset-0 before:bg-gradient-to-br before:from-transparent before:via-yellow-200 before:to-transparent before:opacity-70 before:-translate-x-full before:animate-vibrate-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-double after:border-turquoise-400 after:rounded-3xl after:opacity-80 after:animate-bounce-slow after:-translate-x-full after-hover:translate-x-full clip-path-polygon(10% 10%, 90% 10%, 100% 50%, 90% 90%, 10% 90%, 0% 50%) backdrop-filter backdrop-blur-lg hover:clip-path-polygon(0% 20%, 20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%)\">Chấn động!</button>",
        "classes": "relative inline-flex items-center justify-center p-8 px-16 py-10 overflow-hidden font-display text-4xl text-turquoise-100 bg-gradient-to-r from-indigo-800 via-turquoise-400 to-yellow-500 rounded-3xl border-8 border-dashed border-yellow-300 shadow-3xl transition-all duration-1000 ease-in-out transform hover:-translate-y-4 hover:scale-110 hover:rotate-3 hover:bg-gradient-to-tl hover:shadow-2xl hover:border-double hover:border-turquoise-400 active:translate-y-4 active:scale-90 active:-rotate-3 active:bg-gradient-to-tr active:shadow-sm active:border-dotted active:border-indigo-800 focus:outline-none focus:ring-8 focus:ring-yellow-400 before:absolute before:inset-0 before:bg-gradient-to-br before:from-transparent before:via-yellow-200 before:to-transparent before:opacity-70 before:-translate-x-full before:animate-vibrate-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-double after:border-turquoise-400 after:rounded-3xl after:opacity-80 after:animate-bounce-slow after:-translate-x-full after-hover:translate-x-full clip-path-polygon(10% 10%, 90% 10%, 100% 50%, 90% 90%, 10% 90%, 0% 50%) backdrop-filter backdrop-blur-lg hover:clip-path-polygon(0% 20%, 20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%)"
    },
    {
        "name": "Nút Khảm Xà Cừ",
        "code": "<button class=\"relative inline-flex items-center justify-center p-8 px-16 py-10 overflow-hidden font-serif text-4xl text-teal-100 bg-gradient-to-r from-blue-900 via-emerald-500 to-amber-400 rounded-xl border-8 border-double border-rose-300 shadow-2xl transition-all duration-1000 ease-in-out transform hover:-translate-y-3 hover:scale-110 hover:rotate-12 hover:bg-gradient-to-tl hover:shadow-inner active:translate-y-3 active:scale-95 active:-rotate-6 active:bg-gradient-to-tr active:shadow-sm focus:outline-none focus:ring-8 focus:ring-amber-300 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-rose-200 before:to-transparent before:opacity-60 before:-translate-x-full before:animate-spin-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-emerald-300 after:rounded-xl after:opacity-70 after:animate-ping-slow after:-translate-x-full after-hover:translate-x-full clip-path-polygon(10% 30%, 30% 10%, 70% 10%, 90% 30%, 100% 50%, 90% 70%, 70% 90%, 30% 90%, 10% 70%) backdrop-filter backdrop-blur-md hover:border-solid hover:border-teal-400\">Nút Khảm Xà Cừ</button>",
        "classes": "relative inline-flex items-center justify-center p-8 px-16 py-10 overflow-hidden font-serif text-4xl text-teal-100 bg-gradient-to-r from-blue-900 via-emerald-500 to-amber-400 rounded-xl border-8 border-double border-rose-300 shadow-2xl transition-all duration-1000 ease-in-out transform hover:-translate-y-3 hover:scale-110 hover:rotate-12 hover:bg-gradient-to-tl hover:shadow-inner active:translate-y-3 active:scale-95 active:-rotate-6 active:bg-gradient-to-tr active:shadow-sm focus:outline-none focus:ring-8 focus:ring-amber-300 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-rose-200 before:to-transparent before:opacity-60 before:-translate-x-full before:animate-spin-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-emerald-300 after:rounded-xl after:opacity-70 after:animate-ping-slow after:-translate-x-full after-hover:translate-x-full clip-path-polygon(10% 30%, 30% 10%, 70% 10%, 90% 30%, 100% 50%, 90% 70%, 70% 90%, 30% 90%, 10% 70%) backdrop-filter backdrop-blur-md hover:border-solid hover:border-teal-400"
    },
    {
        "name": "Nút Ảnh Quang",
        "code": "<button class=\"relative inline-flex items-center justify-center p-8 px-16 py-10 overflow-hidden font-display text-5xl text-light-blue-100 bg-gradient-to-r from-violet-800 via-light-blue-400 to-lime-500 rounded-full border-8 border-double border-light-blue-300 shadow-3xl transition-all duration-1000 ease-in-out transform hover:-translate-y-5 hover:scale-115 hover:rotate-6 hover:bg-gradient-to-tl hover:shadow-2xl hover:border-dotted hover:border-lime-400 active:translate-y-5 active:scale-90 active:-rotate-6 active:bg-gradient-to-tr active:shadow-sm active:border-dashed active:border-violet-400 focus:outline-none focus:ring-8 focus:ring-lime-300 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-lime-200 before:to-transparent before:opacity-70 before:-translate-x-full before:animate-pulse-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-double after:border-lime-400 after:rounded-full after:opacity-80 after:animate-bounce after:-translate-x-full after-hover:translate-x-full clip-path-polygon(25% 0%, 100% 25%, 75% 100%, 0% 75%) backdrop-filter backdrop-blur-lg hover:clip-path-polygon(50% 0%, 90% 20%, 100% 60%, 75% 100%, 25% 100%, 0% 60%, 10% 20%) \">Nội dung nút</button>",
        "classes": "relative inline-flex items-center justify-center p-8 px-16 py-10 overflow-hidden font-display text-5xl text-light-blue-100 bg-gradient-to-r from-violet-800 via-light-blue-400 to-lime-500 rounded-full border-8 border-double border-light-blue-300 shadow-3xl transition-all duration-1000 ease-in-out transform hover:-translate-y-5 hover:scale-115 hover:rotate-6 hover:bg-gradient-to-tl hover:shadow-2xl hover:border-dotted hover:border-lime-400 active:translate-y-5 active:scale-90 active:-rotate-6 active:bg-gradient-to-tr active:shadow-sm active:border-dashed active:border-violet-400 focus:outline-none focus:ring-8 focus:ring-lime-300 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-lime-200 before:to-transparent before:opacity-70 before:-translate-x-full before:animate-pulse-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-double after:border-lime-400 after:rounded-full after:opacity-80 after:animate-bounce after:-translate-x-full after-hover:translate-x-full clip-path-polygon(25% 0%, 100% 25%, 75% 100%, 0% 75%) backdrop-filter backdrop-blur-lg hover:clip-path-polygon(50% 0%, 90% 20%, 100% 60%, 75% 100%, 25% 100%, 0% 60%, 10% 20%)"
    },
    {
        "name": "Nút Vũ Trụ",
        "code": "<button class=\"relative inline-flex items-center justify-center p-10 px-20 py-14 overflow-hidden font-mono text-4xl text-white bg-gradient-to-r from-purple-900 via-indigo-500 to-cyan-400 rounded-3xl border-8 border-double border-sky-200 shadow-3xl transition-all duration-1000 ease-in-out transform hover:-translate-y-5 hover:scale-110 hover:rotate-12 hover:bg-gradient-to-tl hover:shadow-inner hover:border-dotted hover:border-fuchsia-300 active:translate-y-5 active:scale-90 active:-rotate-12 active:bg-gradient-to-tr active:shadow-sm active:border-dashed active:border-lime-500 focus:outline-none focus:ring-8 focus:ring-yellow-400 before:absolute before:inset-0 before:bg-gradient-radial from-transparent to-white via-white before:opacity-30 before:-translate-x-full before:animate-pulse-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-orange-400 after:rounded-3xl after:opacity-50 after:animate-bounce-slow after:-translate-x-full after-hover:translate-x-full clip-path-polygon(10% 5%, 30% 0%, 70% 0%, 90% 5%, 100% 25%, 90% 50%, 100% 75%, 90% 95%, 70% 100%, 30% 100%, 10% 95%, 0% 75%, 0% 25%) backdrop-filter backdrop-blur-xl hover:clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%)\">Khám phá</button>",
        "classes": "relative inline-flex items-center justify-center p-10 px-20 py-14 overflow-hidden font-mono text-4xl text-white bg-gradient-to-r from-purple-900 via-indigo-500 to-cyan-400 rounded-3xl border-8 border-double border-sky-200 shadow-3xl transition-all duration-1000 ease-in-out transform hover:-translate-y-5 hover:scale-110 hover:rotate-12 hover:bg-gradient-to-tl hover:shadow-inner hover:border-dotted hover:border-fuchsia-300 active:translate-y-5 active:scale-90 active:-rotate-12 active:bg-gradient-to-tr active:shadow-sm active:border-dashed active:border-lime-500 focus:outline-none focus:ring-8 focus:ring-yellow-400 before:absolute before:inset-0 before:bg-gradient-radial from-transparent to-white via-white before:opacity-30 before:-translate-x-full before:animate-pulse-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-orange-400 after:rounded-3xl after:opacity-50 after:animate-bounce-slow after:-translate-x-full after-hover:translate-x-full clip-path-polygon(10% 5%, 30% 0%, 70% 0%, 90% 5%, 100% 25%, 90% 50%, 100% 75%, 90% 95%, 70% 100%, 30% 100%, 10% 95%, 0% 75%, 0% 25%) backdrop-filter backdrop-blur-xl hover:clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%)"
    },
    {
        "name": "Nút Plasma",
        "code": "<button class=\"relative inline-flex items-center justify-center p-12 px-20 py-12 overflow-hidden font-display text-6xl text-amber-100 bg-gradient-to-r from-indigo-900 via-fuchsia-500 to-yellow-300 rounded-2xl border-8 border-double border-fuchsia-400 shadow-3xl transition-all duration-1200 ease-in-out transform hover:-translate-y-6 hover:scale-125 hover:rotate-15 hover:bg-gradient-to-tr hover:shadow-2xl hover:border-dotted hover:border-amber-300 active:translate-y-6 active:scale-80 active:-rotate-15 active:bg-gradient-to-bl active:shadow-sm active:border-dashed active:border-yellow-200 focus:outline-none focus:ring-8 focus:ring-indigo-600 before:absolute before:inset-0 before:bg-gradient-radial from-transparent to-amber-200 via-fuchsia-100 before:opacity-40 before:-translate-x-full before:animate-pulse-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-double after:border-amber-200 after:rounded-2xl after:opacity-60 after:animate-glow-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-xl hover:clip-path-polygon(0% 10%, 10% 0%, 90% 0%, 100% 10%, 100% 90%, 90% 100%, 10% 100%, 0% 90%)\">Plasma!</button>",
        "classes": "relative inline-flex items-center justify-center p-12 px-20 py-12 overflow-hidden font-display text-6xl text-amber-100 bg-gradient-to-r from-indigo-900 via-fuchsia-500 to-yellow-300 rounded-2xl border-8 border-double border-fuchsia-400 shadow-3xl transition-all duration-1200 ease-in-out transform hover:-translate-y-6 hover:scale-125 hover:rotate-15 hover:bg-gradient-to-tr hover:shadow-2xl hover:border-dotted hover:border-amber-300 active:translate-y-6 active:scale-80 active:-rotate-15 active:bg-gradient-to-bl active:shadow-sm active:border-dashed active:border-yellow-200 focus:outline-none focus:ring-8 focus:ring-indigo-600 before:absolute before:inset-0 before:bg-gradient-radial from-transparent to-amber-200 via-fuchsia-100 before:opacity-40 before:-translate-x-full before:animate-pulse-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-double after:border-amber-200 after:rounded-2xl after:opacity-60 after:animate-glow-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-xl hover:clip-path-polygon(0% 10%, 10% 0%, 90% 0%, 100% 10%, 100% 90%, 90% 100%, 10% 100%, 0% 90%)"
    },
    {
        "name": "Nút Cánh Hoa Rực Rỡ",
        "code": "<button class=\"relative inline-flex items-center justify-center p-8 px-16 py-10 overflow-hidden font-serif text-4xl text-white bg-gradient-to-r from-lime-500 via-orange-400 to-red-600 to-violet-700 rounded-3xl border-8 border-double border-lime-200 shadow-3xl transition-all duration-1000 ease-in-out transform hover:-translate-y-3 hover:scale-110 hover:rotate-8 hover:bg-gradient-to-bl hover:shadow-inner hover:border-dotted hover:border-red-300 active:translate-y-3 active:scale-95 active:-rotate-8 active:bg-gradient-to-tr active:shadow-sm active:border-dashed active:border-violet-400 focus:outline-none focus:ring-8 focus:ring-orange-300 before:absolute before:inset-0 before:bg-gradient-to-br before:from-transparent before:via-orange-200 before:to-transparent before:opacity-60 before:-translate-x-full before:animate-scale-in-horizontally-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-red-400 after:rounded-3xl after:opacity-70 after:animate-scale-in-horizontally-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(50% 0%, 61% 35%, 98% 35%, 68% 57%, 79% 91%, 50% 70%, 21% 91%, 32% 57%, 2% 35%, 39% 35%) backdrop-filter backdrop-blur-md hover:clip-path-polygon(0% 20%, 20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%)\">Nút Cánh Hoa</button>",
        "classes": "relative inline-flex items-center justify-center p-8 px-16 py-10 overflow-hidden font-serif text-4xl text-white bg-gradient-to-r from-lime-500 via-orange-400 to-red-600 to-violet-700 rounded-3xl border-8 border-double border-lime-200 shadow-3xl transition-all duration-1000 ease-in-out transform hover:-translate-y-3 hover:scale-110 hover:rotate-8 hover:bg-gradient-to-bl hover:shadow-inner hover:border-dotted hover:border-red-300 active:translate-y-3 active:scale-95 active:-rotate-8 active:bg-gradient-to-tr active:shadow-sm active:border-dashed active:border-violet-400 focus:outline-none focus:ring-8 focus:ring-orange-300 before:absolute before:inset-0 before:bg-gradient-to-br before:from-transparent before:via-orange-200 before:to-transparent before:opacity-60 before:-translate-x-full before:animate-scale-in-horizontally-slow before-hover:translate-x-full after:absolute after:inset-0 after:border-4 after:border-dotted after:border-red-400 after:rounded-3xl after:opacity-70 after:animate-scale-in-horizontally-fast after:-translate-x-full after-hover:translate-x-full clip-path-polygon(50% 0%, 61% 35%, 98% 35%, 68% 57%, 79% 91%, 50% 70%, 21% 91%, 32% 57%, 2% 35%, 39% 35%) backdrop-filter backdrop-blur-md hover:clip-path-polygon(0% 20%, 20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%)"
    },
    {
        "name": "Nút Sóng Âm",
        "code": "<button class=\"relative inline-flex items-center justify-center p-0.5 overflow-hidden text-base font-bold text-white rounded-full group bg-gradient-to-tr from-blue-400 to-green-600 hover:bg-gradient-to-bl hover:from-green-600 hover:to-blue-400 active:scale-95 active:bg-gradient-to-br active:from-blue-600 active:to-green-400 focus:outline-none focus:ring-2 focus:ring-green-300 transition-all duration-500 ease-in-out transform hover:scale-105 before:absolute before:inset-0 before:z-10 before:bg-gradient-to-r before:from-transparent before:via-blue-200 before:to-transparent before:opacity-50 before:-translate-x-full before:animate-slide-x before:transition-transform before:duration-700 before:ease-in-out before:group-hover:translate-x-full after:absolute after:inset-0 after:z-0 after:border after:border-blue-500 after:opacity-20 after:animate-pulse after:transition-opacity after:duration-1000 after:ease-in-out after:group-hover:opacity-70\">Sóng Âm</button>",
        "classes": "relative inline-flex items-center justify-center p-0.5 overflow-hidden text-base font-bold text-white rounded-full group bg-gradient-to-tr from-blue-400 to-green-600 hover:bg-gradient-to-bl hover:from-green-600 hover:to-blue-400 active:scale-95 active:bg-gradient-to-br active:from-blue-600 active:to-green-400 focus:outline-none focus:ring-2 focus:ring-green-300 transition-all duration-500 ease-in-out transform hover:scale-105 before:absolute before:inset-0 before:z-10 before:bg-gradient-to-r before:from-transparent before:via-blue-200 before:to-transparent before:opacity-50 before:-translate-x-full before:animate-slide-x before:transition-transform before:duration-700 before:ease-in-out before:group-hover:translate-x-full after:absolute after:inset-0 after:z-0 after:border after:border-blue-500 after:opacity-20 after:animate-pulse after:transition-opacity after:duration-1000 after:ease-in-out after:group-hover:opacity-70"
    },
    {
        "name": "Nút Khúc Xạ",
        "code": "<button class=\"relative inline-flex items-center justify-center px-6 py-3 overflow-hidden font-medium text-indigo-50 transition duration-500 ease-in-out transform bg-gradient-to-tl from-cyan-500 via-blue-600 to-purple-700 rounded-full shadow-md hover:scale-105 hover:shadow-xl hover:bg-gradient-to-br active:scale-95 active:shadow active:bg-gradient-to-tr focus:outline-none focus:ring-4 focus:ring-purple-300 before:absolute before:inset-0 before:z-0 before:mix-blend-multiply before:bg-gradient-conic before:from-yellow-500 before:via-orange-500 before:to-red-600 before:opacity-20 before:animate-spin-slow before:transition-opacity before:duration-1000 before:ease-in-out before:group-hover:opacity-50 after:absolute after:inset-0 after:z-10 after:border-2 after:border-dashed after:border-purple-800 after:rounded-full after:opacity-10 after:animate-pulse-slow after:transition-opacity after:duration-700 after:ease-in-out after:group-hover:opacity-60 clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-sm\">Nút Khúc Xạ</button>",
        "classes": "relative inline-flex items-center justify-center px-6 py-3 overflow-hidden font-medium text-indigo-50 transition duration-500 ease-in-out transform bg-gradient-to-tl from-cyan-500 via-blue-600 to-purple-700 rounded-full shadow-md hover:scale-105 hover:shadow-xl hover:bg-gradient-to-br active:scale-95 active:shadow active:bg-gradient-to-tr focus:outline-none focus:ring-4 focus:ring-purple-300 before:absolute before:inset-0 before:z-0 before:mix-blend-multiply before:bg-gradient-conic before:from-yellow-500 before:via-orange-500 before:to-red-600 before:opacity-20 before:animate-spin-slow before:transition-opacity before:duration-1000 before:ease-in-out before:group-hover:opacity-50 after:absolute after:inset-0 after:z-10 after:border-2 after:border-dashed after:border-purple-800 after:rounded-full after:opacity-10 after:animate-pulse-slow after:transition-opacity after:duration-700 after:ease-in-out after:group-hover:opacity-60 clip-path-polygon(20% 0%, 80% 0%, 100% 20%, 100% 80%, 80% 100%, 20% 100%, 0% 80%, 0% 20%) backdrop-filter backdrop-blur-sm"
    },
    {
        "name": "Nút Lấp Lánh",
        "code": "<button class=\"relative inline-flex items-center justify-center px-8 py-4 overflow-hidden font-semibold text-xl text-lime-200 transition duration-700 ease-in-out transform bg-gradient-to-br from-gray-900 via-lime-600 to-green-800 rounded-full border-4 border-dashed border-lime-300 shadow-xl hover:scale-110 hover:shadow-2xl hover:bg-gradient-to-tl hover:border-double hover:border-lime-500 active:scale-95 active:shadow-sm active:bg-gradient-to-tr active:border-dashed active:border-lime-300 focus:outline-none focus:ring-4 focus:ring-lime-400 before:absolute before:inset-0 before:bg-gradient-conic before:from-yellow-400 before:via-lime-500 before:to-green-600 before:opacity-30 before:animate-spin-slow before:transition-opacity before:duration-1000 before:ease-in-out before:blur-lg before:group-hover:opacity-70 after:absolute after:w-20 after:h-20 after:bg-gradient-radial after:from-lime-300 after:to-transparent after:blur-xl after:animate-ping-slow after:transition-all after:duration-500 after:ease-in-out after:group-hover:scale-150 clip-path-polygon(10% 0%, 100% 0%, 90% 100%, 0% 100%) backdrop-filter backdrop-blur-md\">Nút Lấp Lánh</button>",
        "classes": "relative inline-flex items-center justify-center px-8 py-4 overflow-hidden font-semibold text-xl text-lime-200 transition duration-700 ease-in-out transform bg-gradient-to-br from-gray-900 via-lime-600 to-green-800 rounded-full border-4 border-dashed border-lime-300 shadow-xl hover:scale-110 hover:shadow-2xl hover:bg-gradient-to-tl hover:border-double hover:border-lime-500 active:scale-95 active:shadow-sm active:bg-gradient-to-tr active:border-dashed active:border-lime-300 focus:outline-none focus:ring-4 focus:ring-lime-400 before:absolute before:inset-0 before:bg-gradient-conic before:from-yellow-400 before:via-lime-500 before:to-green-600 before:opacity-30 before:animate-spin-slow before:transition-opacity before:duration-1000 before:ease-in-out before:blur-lg before:group-hover:opacity-70 after:absolute after:w-20 after:h-20 after:bg-gradient-radial after:from-lime-300 after:to-transparent after:blur-xl after:animate-ping-slow after:transition-all after:duration-500 after:ease-in-out after:group-hover:scale-150 clip-path-polygon(10% 0%, 100% 0%, 90% 100%, 0% 100%) backdrop-filter backdrop-blur-md"
    },
    {
        "name": "Nút Mắt Kính 3D",
        "code": "<button class=\"relative inline-flex items-center justify-center px-10 py-5 overflow-hidden font-bold text-rose-700 transition-all duration-500 ease-in-out transform bg-gradient-to-bl from-yellow-200 via-red-400 to-purple-600 rounded-xl border-4 border-double border-rose-300 shadow-2xl hover:scale-110 hover:shadow-xl hover:border-dotted hover:border-yellow-400 hover:-translate-y-1 active:scale-90 active:shadow-sm active:translate-y-1 active:border-dashed active:border-red-600 focus:outline-none focus:ring-4 focus:ring-purple-500 before:absolute before:inset-0 before:z-0 before:bg-gradient-to-r before:from-transparent before:via-red-300 before:to-transparent before:opacity-70 before:-translate-x-full before:animate-pulse before:transition-transform before:duration-700 before:ease-in-out before:group-hover:translate-x-full after:absolute after:inset-0 after:z-10 after:border-4 after:border-dotted after:border-yellow-600 after:rounded-xl after:opacity-60 after:animate-shimmer-slow after:transition-opacity after:duration-500 after:ease-in-out after:group-hover:opacity-90 clip-path-polygon(10% 0, 50% 0, 90% 0, 100% 50%, 90% 100%, 50% 100%, 10% 100%, 0 50%) backdrop-filter backdrop-blur-md\">Xem 3D</button>",
        "classes": "relative inline-flex items-center justify-center px-10 py-5 overflow-hidden font-bold text-rose-700 transition-all duration-500 ease-in-out transform bg-gradient-to-bl from-yellow-200 via-red-400 to-purple-600 rounded-xl border-4 border-double border-rose-300 shadow-2xl hover:scale-110 hover:shadow-xl hover:border-dotted hover:border-yellow-400 hover:-translate-y-1 active:scale-90 active:shadow-sm active:translate-y-1 active:border-dashed active:border-red-600 focus:outline-none focus:ring-4 focus:ring-purple-500 before:absolute before:inset-0 before:z-0 before:bg-gradient-to-r before:from-transparent before:via-red-300 before:to-transparent before:opacity-70 before:-translate-x-full before:animate-pulse before:transition-transform before:duration-700 before:ease-in-out before:group-hover:translate-x-full after:absolute after:inset-0 after:z-10 after:border-4 after:border-dotted after:border-yellow-600 after:rounded-xl after:opacity-60 after:animate-shimmer-slow after:transition-opacity after:duration-500 after:ease-in-out after:group-hover:opacity-90 clip-path-polygon(10% 0, 50% 0, 90% 0, 100% 50%, 90% 100%, 50% 100%, 10% 100%, 0 50%) backdrop-filter backdrop-blur-md"
    },
    {
        "name": "Nút Khối Lập Phương Xoay",
        "code": "<button class=\"relative inline-flex items-center justify-center w-20 h-20 overflow-hidden bg-gradient-to-r from-purple-500 to-pink-500 rounded-lg shadow-xl transform transition-all duration-500 hover:scale-105 hover:shadow-2xl active:scale-95 focus:outline-none focus:ring-2 focus:ring-pink-300 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-purple-300 before:to-transparent before:opacity-50 before:blur-lg before:animate-spin-slow after:content-[''] after:absolute after:w-8 after:h-8 after:top-1/2 after:left-1/2 after:-translate-x-1/2 after:-translate-y-1/2 after:bg-white after:rounded-full after:opacity-20 after:animate-pulse clip-path-polygon(10% 0, 90% 0, 100% 10%, 100% 90%, 90% 100%, 10% 100%, 0 90%, 0 10%) backdrop-filter backdrop-blur-md\">Nhấn</button>",
        "classes": "relative inline-flex items-center justify-center w-20 h-20 overflow-hidden bg-gradient-to-r from-purple-500 to-pink-500 rounded-lg shadow-xl transform transition-all duration-500 hover:scale-105 hover:shadow-2xl active:scale-95 focus:outline-none focus:ring-2 focus:ring-pink-300 before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-purple-300 before:to-transparent before:opacity-50 before:blur-lg before:animate-spin-slow after:content-[''] after:absolute after:w-8 after:h-8 after:top-1/2 after:left-1/2 after:-translate-x-1/2 after:-translate-y-1/2 after:bg-white after:rounded-full after:opacity-20 after:animate-pulse clip-path-polygon(10% 0, 90% 0, 100% 10%, 100% 90%, 90% 100%, 10% 100%, 0 90%, 0 10%) backdrop-filter backdrop-blur-md"
    },
    {
        "name": "Nút Mặt Trời",
        "code": "<button class=\"relative inline-flex items-center justify-center px-10 py-4 overflow-hidden font-bold text-yellow-100 bg-gradient-to-br from-yellow-300 via-orange-500 to-red-600 rounded-full border-4 border-solid border-yellow-400 shadow-2xl transition-all duration-700 ease-in-out transform hover:-translate-y-1 hover:scale-110 hover:shadow-xl hover:bg-gradient-to-tl hover:border-orange-600 active:translate-y-1 active:scale-95 active:shadow-sm active:bg-gradient-to-tr active:border-yellow-200 focus:outline-none focus:ring-4 focus:ring-red-500 before:absolute before:inset-0 before:bg-gradient-radial before:from-yellow-200 before:via-orange-400 before:to-red-500 before:opacity-60 before:blur-md before:-translate-y-full before:animate-pulse-slow before:group-hover:translate-y-0 after:absolute after:inset-0 after:border-4 after:border-dashed after:border-red-700 after:rounded-full after:opacity-30 after:animate-pulse-fast after:-translate-x-full after:group-hover:translate-x-0 clip-path-polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%) backdrop-filter backdrop-blur-lg\">Nút Mặt Trời</button>",
        "classes": "relative inline-flex items-center justify-center px-10 py-4 overflow-hidden font-bold text-yellow-100 bg-gradient-to-br from-yellow-300 via-orange-500 to-red-600 rounded-full border-4 border-solid border-yellow-400 shadow-2xl transition-all duration-700 ease-in-out transform hover:-translate-y-1 hover:scale-110 hover:shadow-xl hover:bg-gradient-to-tl hover:border-orange-600 active:translate-y-1 active:scale-95 active:shadow-sm active:bg-gradient-to-tr active:border-yellow-200 focus:outline-none focus:ring-4 focus:ring-red-500 before:absolute before:inset-0 before:bg-gradient-radial before:from-yellow-200 before:via-orange-400 before:to-red-500 before:opacity-60 before:blur-md before:-translate-y-full before:animate-pulse-slow before:group-hover:translate-y-0 after:absolute after:inset-0 after:border-4 after:border-dashed after:border-red-700 after:rounded-full after:opacity-30 after:animate-pulse-fast after:-translate-x-full after:group-hover:translate-x-0 clip-path-polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%) backdrop-filter backdrop-blur-lg"
    },
    {
        "name": "Nút Mộng Mơ",
        "code": "<button class=\"relative inline-flex items-center justify-center px-6 py-3 overflow-hidden font-mono text-xl text-indigo-200 transition duration-700 ease-in-out transform bg-gradient-to-br from-green-400 via-teal-500 to-blue-700 rounded-3xl border-4 border-double border-green-600 shadow-xl hover:scale-110 hover:shadow-2xl hover:bg-gradient-to-tl active:scale-95 active:shadow-sm active:bg-gradient-to-tr focus:outline-none focus:ring-4 focus:ring-blue-400 before:absolute before:inset-0 before:bg-gradient-conic before:from-yellow-300 before:via-lime-400 before:to-green-500 before:opacity-40 before:animate-spin-slow before:transition before:duration-1000 before:blur-md before:group-hover:opacity-80 after:absolute after:inset-y-0 after:left-0 after:w-1/3 after:bg-gradient-to-r after:from-transparent after:via-blue-300 after:to-transparent after:opacity-60 after:animate-pulse-slow after:transition after:duration-700 after:group-hover:w-full clip-path-polygon(0% 20%, 60% 0%, 100% 20%, 100% 80%, 60% 100%, 0% 80%) backdrop-filter backdrop-blur-lg\">Nút Mộng Mơ</button>",
        "classes": "relative inline-flex items-center justify-center px-6 py-3 overflow-hidden font-mono text-xl text-indigo-200 transition duration-700 ease-in-out transform bg-gradient-to-br from-green-400 via-teal-500 to-blue-700 rounded-3xl border-4 border-double border-green-600 shadow-xl hover:scale-110 hover:shadow-2xl hover:bg-gradient-to-tl active:scale-95 active:shadow-sm active:bg-gradient-to-tr focus:outline-none focus:ring-4 focus:ring-blue-400 before:absolute before:inset-0 before:bg-gradient-conic before:from-yellow-300 before:via-lime-400 before:to-green-500 before:opacity-40 before:animate-spin-slow before:transition before:duration-1000 before:blur-md before:group-hover:opacity-80 after:absolute after:inset-y-0 after:left-0 after:w-1/3 after:bg-gradient-to-r after:from-transparent after:via-blue-300 after:to-transparent after:opacity-60 after:animate-pulse-slow after:transition after:duration-700 after:group-hover:w-full clip-path-polygon(0% 20%, 60% 0%, 100% 20%, 100% 80%, 60% 100%, 0% 80%) backdrop-filter backdrop-blur-lg"
    },
    {
        "name": "Nút Lân Tinh",
        "code": "<button class=\"relative inline-flex items-center justify-center px-8 py-4 overflow-hidden font-semibold text-xl text-indigo-600 transition-all duration-500 ease-in-out transform bg-gradient-to-br from-sky-300 via-purple-400 to-orange-500 rounded-full border-4 border-double border-sky-600 shadow-xl group hover:scale-110 hover:shadow-2xl hover:rotate-6 hover:bg-gradient-to-tl active:scale-95 active:shadow-sm active:bg-gradient-to-tr active:rotate-12 focus:outline-none focus:ring-4 focus:ring-orange-400 before:absolute before:inset-0 before:bg-gradient-conic before:from-violet-500 before:via-purple-500 before:to-orange-500 before:opacity-50 before:blur-lg before:animate-spin-slow before:group-hover:opacity-80 after:absolute after:inset-0 after:border-4 after:border-solid after:border-orange-700 after:opacity-60 after:animate-pulse after:transition after:duration-700 after:group-hover:opacity-10 after:group-hover:scale-125 clip-path-polygon(10% 0, 90% 0, 100% 50%, 90% 100%, 10% 100%, 0% 50%) backdrop-filter backdrop-blur-md\">Nút Lân Tinh</button>",
        "classes": "relative inline-flex items-center justify-center px-8 py-4 overflow-hidden font-semibold text-xl text-indigo-600 transition-all duration-500 ease-in-out transform bg-gradient-to-br from-sky-300 via-purple-400 to-orange-500 rounded-full border-4 border-double border-sky-600 shadow-xl group hover:scale-110 hover:shadow-2xl hover:rotate-6 hover:bg-gradient-to-tl active:scale-95 active:shadow-sm active:bg-gradient-to-tr active:rotate-12 focus:outline-none focus:ring-4 focus:ring-orange-400 before:absolute before:inset-0 before:bg-gradient-conic before:from-violet-500 before:via-purple-500 before:to-orange-500 before:opacity-50 before:blur-lg before:animate-spin-slow before:group-hover:opacity-80 after:absolute after:inset-0 after:border-4 after:border-solid after:border-orange-700 after:opacity-60 after:animate-pulse after:transition after:duration-700 after:group-hover:opacity-10 after:group-hover:scale-125 clip-path-polygon(10% 0, 90% 0, 100% 50%, 90% 100%, 10% 100%, 0% 50%) backdrop-filter backdrop-blur-md"
    },
    {
        "name": "Nút Mặt Nước Gợn Sóng",
        "code": "<button class=\"relative inline-flex items-center justify-center px-10 py-5 overflow-hidden font-mono text-2xl text-gray-900 transition duration-500 ease-in-out transform bg-gradient-to-br from-teal-300 via-cyan-400 to-blue-500 rounded-full border-4 border-double border-teal-600 shadow-xl hover:scale-105 hover:shadow-2xl hover:bg-gradient-to-tl active:scale-95 active:shadow-sm active:bg-gradient-to-tr focus:outline-none focus:ring-4 focus:ring-cyan-400 before:absolute before:inset-0 before:bg-gradient-radial before:from-cyan-200 before:via-blue-300 before:to-transparent before:opacity-60 before:blur-md before:animate-ripple before:transition before:duration-700 after:absolute after:inset-0 after:border-4 after:border-dashed after:border-teal-700 after:rounded-full after:opacity-50 after:animate-pulse after:transition after:duration-500 clip-path-ellipse(60% 40% at 50% 50%) backdrop-filter backdrop-blur-sm\">Nút</button>",
        "classes": "relative inline-flex items-center justify-center px-10 py-5 overflow-hidden font-mono text-2xl text-gray-900 transition duration-500 ease-in-out transform bg-gradient-to-br from-teal-300 via-cyan-400 to-blue-500 rounded-full border-4 border-double border-teal-600 shadow-xl hover:scale-105 hover:shadow-2xl hover:bg-gradient-to-tl active:scale-95 active:shadow-sm active:bg-gradient-to-tr focus:outline-none focus:ring-4 focus:ring-cyan-400 before:absolute before:inset-0 before:bg-gradient-radial before:from-cyan-200 before:via-blue-300 before:to-transparent before:opacity-60 before:blur-md before:animate-ripple before:transition before:duration-700 after:absolute after:inset-0 after:border-4 after:border-dashed after:border-teal-700 after:rounded-full after:opacity-50 after:animate-pulse after:transition after:duration-500 clip-path-ellipse(60% 40% at 50% 50%) backdrop-filter backdrop-blur-sm"
    },
    {
        "name": "Nút Mạt Chược",
        "code": "<button class=\"relative inline-flex items-center justify-center px-6 py-3 overflow-hidden font-bold text-lg text-gray-800 transition-all duration-300 ease-in-out transform bg-gradient-to-br from-green-300 via-lime-400 to-yellow-500 rounded-full border-4 border-double border-green-700 shadow-xl hover:scale-110 hover:shadow-2xl hover:rotate-12 hover:bg-gradient-to-tl hover:border-lime-700 active:scale-90 active:shadow-sm active:bg-gradient-to-tr active:border-green-500 focus:outline-none focus:ring-4 focus:ring-yellow-400 before:absolute before:inset-0 before:bg-gradient-conic before:from-yellow-300 before:via-lime-500 before:to-green-600 before:opacity-40 before:blur-lg before:animate-wiggle-slow before:transition before:duration-700 after:absolute after:inset-0 after:border after:border-green-800 after:opacity-40 after:animate-pulse-faster after:transition after:duration-500 clip-path-polygon(50% 0%, 100% 20%, 80% 100%, 20% 100%, 0% 80%) backdrop-filter backdrop-blur-sm\">Mạt Chược</button>",
        "classes": "relative inline-flex items-center justify-center px-6 py-3 overflow-hidden font-bold text-lg text-gray-800 transition-all duration-300 ease-in-out transform bg-gradient-to-br from-green-300 via-lime-400 to-yellow-500 rounded-full border-4 border-double border-green-700 shadow-xl hover:scale-110 hover:shadow-2xl hover:rotate-12 hover:bg-gradient-to-tl hover:border-lime-700 active:scale-90 active:shadow-sm active:bg-gradient-to-tr active:border-green-500 focus:outline-none focus:ring-4 focus:ring-yellow-400 before:absolute before:inset-0 before:bg-gradient-conic before:from-yellow-300 before:via-lime-500 before:to-green-600 before:opacity-40 before:blur-lg before:animate-wiggle-slow before:transition before:duration-700 after:absolute after:inset-0 after:border after:border-green-800 after:opacity-40 after:animate-pulse-faster after:transition after:duration-500 clip-path-polygon(50% 0%, 100% 20%, 80% 100%, 20% 100%, 0% 80%) backdrop-filter backdrop-blur-sm"
    },
    {
        "name": "Nút Lục Bảo Huyền Bí",
        "code": "<button class=\"relative inline-flex items-center justify-center px-10 py-4 overflow-hidden font-bold text-xl text-emerald-100 transition-all duration-500 ease-in-out transform bg-gradient-to-bl from-cyan-600 via-teal-400 to-green-700 rounded-full border-4 border-double border-teal-300 shadow-xl hover:scale-110 hover:shadow-2xl hover:border-dotted hover:border-cyan-400 hover:-translate-y-2 active:scale-90 active:shadow-sm active:translate-y-2 active:border-dashed active:border-teal-600 focus:outline-none focus:ring-4 focus:ring-green-500 before:absolute before:inset-0 before:z-0 before:bg-gradient-to-r before:from-transparent before:via-teal-200 before:to-transparent before:opacity-80 before:-translate-x-full before:animate-slide-x before:transition-transform before:duration-700 before:ease-in-out before:group-hover:translate-x-full after:absolute after:inset-0 after:z-10 after:border-4 after:border-dotted after:border-cyan-600 after:rounded-full after:opacity-60 after:animate-shimmer-slow after:transition-opacity after:duration-500 after:ease-in-out after:group-hover:opacity-90 clip-path-polygon(0% 0%, 100% 0%, 100% 75%, 75% 100%, 0% 100%) backdrop-filter backdrop-blur-md\">Nút Bấm</button>",
        "classes": "relative inline-flex items-center justify-center px-10 py-4 overflow-hidden font-bold text-xl text-emerald-100 transition-all duration-500 ease-in-out transform bg-gradient-to-bl from-cyan-600 via-teal-400 to-green-700 rounded-full border-4 border-double border-teal-300 shadow-xl hover:scale-110 hover:shadow-2xl hover:border-dotted hover:border-cyan-400 hover:-translate-y-2 active:scale-90 active:shadow-sm active:translate-y-2 active:border-dashed active:border-teal-600 focus:outline-none focus:ring-4 focus:ring-green-500 before:absolute before:inset-0 before:z-0 before:bg-gradient-to-r before:from-transparent before:via-teal-200 before:to-transparent before:opacity-80 before:-translate-x-full before:animate-slide-x before:transition-transform before:duration-700 before:ease-in-out before:group-hover:translate-x-full after:absolute after:inset-0 after:z-10 after:border-4 after:border-dotted after:border-cyan-600 after:rounded-full after:opacity-60 after:animate-shimmer-slow after:transition-opacity after:duration-500 after:ease-in-out after:group-hover:opacity-90 clip-path-polygon(0% 0%, 100% 0%, 100% 75%, 75% 100%, 0% 100%) backdrop-filter backdrop-blur-md"
    },
    {
        "name": "Nút Lưng Gù",
        "code": "<button class=\"relative inline-flex items-center justify-center px-10 py-4 overflow-hidden font-bold text-purple-200 transition-all duration-500 transform bg-gradient-to-tl from-pink-600 via-purple-800 to-indigo-900 rounded-lg shadow-2xl hover:scale-110 hover:shadow-xl hover:-translate-y-1 hover:rotate-3 active:scale-95 active:translate-y-1 active:rotate--3 active:shadow-sm focus:outline-none focus:ring-4 focus:ring-indigo-400 before:absolute before:inset-0 before:z-0 before:bg-gradient-to-br before:from-transparent before:via-pink-400 before:to-transparent before:opacity-60 before:-translate-x-full before:animate-slide-x-reverse before:transition before:duration-500 before:group-hover:translate-x-0 after:absolute after:inset-0 after:z-10 after:border-4 after:border-dotted after:border-pink-700 after:rounded-lg after:opacity-40 after:animate-pulse after:transition after:duration-700 after:group-hover:opacity-80 clip-path-polygon(20% 0%, 0% 20%, 30% 50%, 0% 80%, 20% 100%, 50% 70%, 80% 100%, 100% 80%, 70% 50%, 100% 20%, 80% 0%, 50% 30%) backdrop-filter backdrop-blur-md\">Nút Lưng Gù</button>",
        "classes": "relative inline-flex items-center justify-center px-10 py-4 overflow-hidden font-bold text-purple-200 transition-all duration-500 transform bg-gradient-to-tl from-pink-600 via-purple-800 to-indigo-900 rounded-lg shadow-2xl hover:scale-110 hover:shadow-xl hover:-translate-y-1 hover:rotate-3 active:scale-95 active:translate-y-1 active:rotate--3 active:shadow-sm focus:outline-none focus:ring-4 focus:ring-indigo-400 before:absolute before:inset-0 before:z-0 before:bg-gradient-to-br before:from-transparent before:via-pink-400 before:to-transparent before:opacity-60 before:-translate-x-full before:animate-slide-x-reverse before:transition before:duration-500 before:group-hover:translate-x-0 after:absolute after:inset-0 after:z-10 after:border-4 after:border-dotted after:border-pink-700 after:rounded-lg after:opacity-40 after:animate-pulse after:transition after:duration-700 after:group-hover:opacity-80 clip-path-polygon(20% 0%, 0% 20%, 30% 50%, 0% 80%, 20% 100%, 50% 70%, 80% 100%, 100% 80%, 70% 50%, 100% 20%, 80% 0%, 50% 30%) backdrop-filter backdrop-blur-md"
    }
];

export default buttons;
